#Your partner ID to use in during the ordering process.
#Without this you will not be credited for the purchases.
#(Your partner id is not the same as your referral link, please check your client area to find your partner id at https://www.bisecthosting.com/partners/console.php).
partner_id = "2511"
#The id of this modpack.
#(This is BH internal pack id; Find the id here: https://www.bisecthosting.com/partners/console.php)
pack_id = "18317"
#Set this to false to disable pack config screen and enable user configs instead.
#This should always be done by the pack author once they are done with configuring the pack.
#To re-enable Pack Edit Mode, please edit the config file.
pack_edit_mode = false

[modules]

	[modules.server_creator_banner]
		enabled = true

		#Modpack Configs
		[modules.server_creator_banner.pack]
			#The title to display at the top of the entry.
			title = "Need a server to play with your friends?"
			#The description to display below the title.
			description = "§9      ➥§9 Click here to rent your own server.§r\n§7Save 25% on your order with the§6§l VALHELSIA§7 code!"
			#Set this to true to use specific language translation keys.
			#This requires a custom mod that adds resource files, such as OpenLoader.
			#Use 'server_entry.title' key for the Title;
			#Use 'server_entry.description' key for the Description.
			use_language_files = false

	[modules.public_server_list]
		enabled = false

