
["Mob Spawns"]
	#determines how often will Burneds spawn
	"Burned Weight" = 20
	#determines how often will Frostbittens spawn
	"Frostbitten Weight" = 80
	#determines how often will Glacial Hunters spawn
	"Glacial Hunter Weight" = 20
	#determines how often will Swampies spawn
	"Swampy Weight" = 80
	#determines how often will Undead Miners spawn
	"Undead Miner Weight" = 20
	#determines how often will Mummies spawn
	"Mummy Weight" = 0
	#determines how often will Dead Beard spawn
	"Dead Beard Weight" = 1
	#determines the chance of spawning for Immortals
	"Immortal Chance" = 0.025

