
[blocks]
	"Wooden boards" = true
	"Wooden bookshelves" = false
	"Wooden ladders" = false
	"Wooden beehives" = true
	"Wooden chests" = true
	"Leaf piles" = false
	Sawmill = true

[generation]
	#If variant bookshelves replace bookshelves in certain structures
	"Wooden bookshelves in structures" = false
	#If variant ladders replace ladders in certain structures
	"Wooden ladders in structures" = false
	#If variant chests replace chests in certain structures
	"Wooden chests in structres" = true

